# Generated by Django 4.1.1 on 2023-01-22 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activities', models.TextField(blank=True)),
                ('no_of_Hours', models.PositiveIntegerField()),
                ('positon_of_interviewd_person', models.CharField(max_length=500)),
                ('marks', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, upload_to='attachments')),
                ('refer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interview', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
