# Generated by Django 4.1.1 on 2023-01-22 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='marks',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
